Repository johnsonjh/OX153, pull requests merged in 2020-12, with the labels that each got.

#2 Add a Codacy badge to README.md
  README.md
Labels: automation, bot, documentation, enhancement

#6 Add DeepSource Badge
  README.md
Labels: automation, bot, configuration, documentation, low-priority

#9 Tickgit badge
  README.md
Labels: automation, documentation, enhancement, low-priority
